 language: node_js
 node_js:
   - "0.10"

 before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g protractor
  - webdriver-manager update
  - webdriver-manager start
  - npm install

 script: grunt e2e